export default {
  STOP_LOADING: "STOP_LOADING",
  START_LOADING: "START_LOADING",
  START_SUCCESS: "START_SUCCESS",
  STOP_SUCCESS: "STOP_SUCCESS",
  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  LOAD_BOT_NUMS: "LOAD_BOT_NUMS",
  PICKUP_LOCATION: "PICKUP_LOCATION",
  PICKUP_LOCATION_AGAIN: "PICKUP_LOCATION_AGAIN",
  DROPOFF_LOCATION: "DROPOFF_LOCATION",
  DROPOFF_LOCATION_AGAIN: "DROPOFF_LOCATION_AGAIN",
  PICKUP_DATE: "PICKUP_DATE",
  PICKUP_DATE_AGAIN: "PICKUP_DATE_AGAIN",
  PICKUP_TIME: "PICKUP_TIME",
  PICKUP_TIME_AGAIN: "PICKUP_TIME_AGAIN",
  PASSENGER_AMOUNT: "PASSENGER_AMOUNT",
  PASSENGER_AMOUNT_AGAIN: "PASSENGER_AMOUNT_AGAIN",
  FLIGHT: "FLIGHT",
  FLIGHT_AGAIN: "FLIGHT_AGAIN",
  AMOUNT: "AMOUNT",
  AMOUNT_AGAIN: "AMOUNT_AGAIN",
  ROUND_TRIP: "ROUND_TRIP",

  CONTACT_INFO: "CONTACT_INFO",

  //DRIVER REDUCER
  DRIVER_LIST_IN_LORD: "DRIVER_LIST_IN_LORD",
  DRIVER_LOCATION_LIST_IN_LORD: "DRIVER_LOCATION_LIST_IN_LORD",
  CAR_LIST_FOR_A_DRIVER: "CAR_LIST_FOR_A_DRIVER",
  DRIVER_DETAIL_IN_LORD: "DRIVER_DETAIL_IN_LORD",
  DRIVER_PAYABLE_LIST_IN_LORD: "DRIVER_PAYABLE_LIST_IN_LORD",
  //VEHICLE REDUCER
  VEHICLE_LIST_IN_LORD: "VEHICLE_LIST_IN_LORD",
  DRIVER_LIST_FOR_A_CAR: "DRIVER_LIST_FOR_A_CAR",
  VEHICLE_DETAIL_IN_LORD: "VEHICLE_DETAIL_IN_LORD",

  //CUSTOMER REDUCER
  CUSTOMER_LIST_IN_LORD: "CUSTOMER_LIST_IN_LORD",
  CUSTOMER_DETAIL_IN_LORD: "CUSTOMER_DETAIL_IN_LORD",
  //ORDER REDUCER
  ORDER_LIST_IN_LORD: "ORDER_LIST_IN_LORD",
  ORDER_DETAIL: "ORDER_DETAIL",
  CURRENT_ORDER: "CURRENT_ORDER",
  ORDER_LIST_IN_LORD_WITH_DATE: "ORDER_LIST_IN_LORD_WITH_DATE",
  ORDER_LIST_IN_CUSTOMER: "ORDER_LIST_IN_CUSTOMER",
  //TRIP REDUCER
  TRIP_LIST_IN_LORD: "TRIP_LIST_IN_LORD",
  TRIP_ACTIVE_LIST_IN_LORD: "TRIP_ACTIVE_LIST_IN_LORD",
  TRIP_ACTIVE_LIST_IN_DRIVER: "TRIP_ACTIVE_LIST_IN_DRIVER",
  TRIP_LIST_IN_DRIVER: "TRIP_LIST_IN_DRIVER",
  TRIP_DETAIL_IN_LORD: "TRIP_DETAIL_IN_LORD",
  TRIP_DETAIL_IN_LORD_AGAIN: "TRIP_DETAIL_IN_LORD_AGAIN",
  TRIP_COUNT_IN_LORD_ACTIVE: "TRIP_COUNT_IN_LORD_ACTIVE",
  TRIP_COUNT_IN_LORD_FINISHED: "TRIP_COUNT_IN_LORD_FINISHED",
  TRIP_COUNT_IN_LORD_FAILED: "TRIP_COUNT_IN_LORD_FAILED",

  //DRIVERPAYABLE REDUCER
  DRIVER_LOCATION_LIST_IN_LORD_MAP_FALSE: "DRIVER_LOCATION_LIST_IN_LORD_MAP_FALSE",
  //NOTIFICATION REDUCER
  NOTIFICATION_LIKE_IN_LORD: "NOTIFICATION_LIKE_IN_LORD",

  //SETTINGS REDUCER
  COUPON_LIST_IN_SETTINGS: "COUPON_LIST_IN_SETTINGS",
  VEHICLE_TYPE_LIST_IN_SETTINGS: "VEHICLE_TYPE_LIST_IN_SETTINGS",
  GENERAL_LIST_IN_SETTINGS: "GENERAL_LIST_IN_SETTINGS",
  VEHICLE_TYPE_LIST_IN_LORD: "VEHICLE_TYPE_LIST_IN_LORD",

  WAGE_LIST_IN_DRIVER: "WAGE_LIST_IN_DRIVER",
  WAGE_SUM_LIST_IN_DRIVER: "WAGE_SUM_LIST_IN_DRIVER",

  SALARY_LIST_IN_DRIVER: "SALARY_LIST_IN_DRIVER",
  SALARY_SUM_LIST_IN_DRIVER: "SALARY_SUM_LIST_IN_DRIVER",

  REALM_LIST_IN_LORD: "REALM_LIST_IN_LORD",
  PAYMENT_LIST_IN_LORD: "PAYMENT_LIST_IN_LORD",
  MESSAGE_LIST_IN_LORD: "MESSAGE_LIST_IN_LORD",
  EMAIL_LIST_IN_LORD: "EMAIL_LIST_IN_LORD",

  FLIGHT_LIST_IN_LORD: "FLIGHT_LIST_IN_LORD",
  FLIGHT_LIST_IN_LORD_AGAIN: "FLIGHT_LIST_IN_LORD_AGAIN",

  QUOTE_IN_LORD: "QUOTE_IN_LORD",
  QUOTE_IN_LORD_SET_MAP: "QUOTE_IN_LORD_SET_MAP",
  QUOTE_IN_LORD_AGAIN: "QUOTE_IN_LORD_AGAIN",
  QUOTE_IN_LORD_SET_MAP_AGAIN: "QUOTE_IN_LORD_SET_MAP_AGAIN",

  COUPON_LIST_IN_LORD: "COUPON_LIST_IN_LORD",

  NOTE_LIST_FOR_CUSTOMER: "NOTE_LIST_FOR_CUSTOMER",
  NOTE_LIST_FOR_TRIP: "NOTE_LIST_FOR_TRIP",
  NOTE_LIST_FOR_ORDER: "NOTE_LIST_FOR_ORDER",

  GENERAL_SETTING_LIST_IN_LORD: "GENERAL_SETTING_LIST_IN_LORD"
};
