export default {
  STOP_LOADING: "STOP_LOADING",
  START_LOADING: "START_LOADING",
  START_SUCCESS: "START_SUCCESS",
  STOP_SUCCESS: "STOP_SUCCESS",
  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  LOAD_BOT_NUMS: "LOAD_BOT_NUMS",
  PICKUP_LOCATION: "PICKUP_LOCATION",
  PICKUP_LOCATION_AGAIN: "PICKUP_LOCATION_AGAIN",
  DROPOFF_LOCATION: "DROPOFF_LOCATION",
  DROPOFF_LOCATION_AGAIN: "DROPOFF_LOCATION_AGAIN",
  PICKUP_DATE: "PICKUP_DATE",
  PICKUP_DATE_AGAIN: "PICKUP_DATE_AGAIN",
  PICKUP_TIME: "PICKUP_TIME",
  PICKUP_TIME_AGAIN: "PICKUP_TIME_AGAIN",
  PASSENGER_AMOUNT: "PASSENGER_AMOUNT",
  PASSENGER_AMOUNT_AGAIN: "PASSENGER_AMOUNT_AGAIN",
  FLIGHT: "FLIGHT",
  FLIGHT_AGAIN: "FLIGHT_AGAIN",
  AMOUNT: "AMOUNT",
  AMOUNT_AGAIN: "AMOUNT_AGAIN",
  ROUND_TRIP: "ROUND_TRIP",

  CONTACT_INFO: "CONTACT_INFO",

  //DRIVER REDUCER
  DRIVER_LIST_IN_LORD: "DRIVER_LIST_IN_LORD",
  DRIVER_LOCATION_LIST_IN_LORD: "DRIVER_LOCATION_LIST_IN_LORD",
  CAR_LIST_FOR_A_DRIVER: "CAR_LIST_FOR_A_DRIVER",
  DRIVER_DETAIL_IN_LORD: "DRIVER_DETAIL_IN_LORD",

  //VEHICLE REDUCER
  VEHICLE_LIST_IN_LORD: "VEHICLE_LIST_IN_LORD",
  DRIVER_LIST_FOR_A_CAR: "DRIVER_LIST_FOR_A_CAR",
  VEHICLE_DETAIL_IN_LORD: "VEHICLE_DETAIL_IN_LORD",

  //CUSTOMER REDUCER
  CUSTOMER_LIST_IN_LORD: "CUSTOMER_LIST_IN_LORD",
  CUSTOMER_DETAIL_IN_LORD: "CUSTOMER_DETAIL_IN_LORD",
  //ORDER REDUCER
  ORDER_LIST_IN_LORD: "ORDER_LIST_IN_LORD",

  //TRIP REDUCER
  TRIP_LIST_IN_LORD: "TRIP_LIST_IN_LORD",
  TRIP_ACTIVE_LIST_IN_DRIVER: "TRIP_ACTIVE_LIST_IN_DRIVER",
  TRIP_LIST_IN_DRIVER: "TRIP_LIST_IN_DRIVER",
  TRIP_DETAIL_IN_LORD: "TRIP_DETAIL_IN_LORD",
  //DRIVERPAYABLE REDUCER
  DRIVER_PAYABLE_LIST_IN_LORD: "DRIVER_PAYABLE_LIST_IN_LORD",

  //NOTIFICATION REDUCER
  NOTIFICATION_LIKE_IN_LORD: "NOTIFICATION_LIKE_IN_LORD",

  //SETTINGS REDUCER
  COUPON_LIST_IN_SETTINGS: "COUPON_LIST_IN_SETTINGS",
  VEHICLE_TYPE_LIST_IN_SETTINGS: "VEHICLE_TYPE_LIST_IN_SETTINGS",
  GENERAL_LIST_IN_SETTINGS: "GENERAL_LIST_IN_SETTINGS"
};
